<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVJ2nQwl\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVJ2nQwl/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVJ2nQwl.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVJ2nQwl\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVJ2nQwl\appAppKernelProdContainer([
    'container.build_hash' => 'VJ2nQwl',
    'container.build_id' => '7778332f',
    'container.build_time' => 1727842052,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVJ2nQwl');
