<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container01J0Odq\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container01J0Odq/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container01J0Odq.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container01J0Odq\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container01J0Odq\appAppKernelProdContainer([
    'container.build_hash' => '01J0Odq',
    'container.build_id' => '7f4f8ca5',
    'container.build_time' => 1731994803,
], __DIR__.\DIRECTORY_SEPARATOR.'Container01J0Odq');
