<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1KaIMOF\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1KaIMOF/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container1KaIMOF.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container1KaIMOF\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container1KaIMOF\appAppKernelProdContainer([
    'container.build_hash' => '1KaIMOF',
    'container.build_id' => 'e4e59373',
    'container.build_time' => 1729494854,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1KaIMOF');
