<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR18uj5C\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR18uj5C/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerR18uj5C.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerR18uj5C\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerR18uj5C\appAppKernelProdContainer([
    'container.build_hash' => 'R18uj5C',
    'container.build_id' => 'af067bc4',
    'container.build_time' => 1732002468,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR18uj5C');
